modLoader = "javafml" #mandatory
loaderVersion = "[41,)" #mandatory
license = "MIT"
issueTrackerURL = "https://github.com/StrikerRockers-Mods/SBM-JukeBox/issues"
displayURL = "http://minecraft.curseforge.com/projects/sbm-jukebox"
authors = "StrikerRocker"

[[mods]] #mandatory
modId = "sbmjukebox" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "[SBM] Jukebox" #mandatory
description = '''Simple mod that makes the jukebox inventory accessible''' #mandatory

[[dependencies.sbmjukebox]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sbmjukebox]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"