name: "Java CI"
on:
  push:
    branches:
      - '[0-9]**'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.gitignore'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '.github/**'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: burrunan/gradle-cache-action@v1
        name: Build with Gradle
        id: build
        with:
          arguments: "build"
          gradle-version: "wrapper"