name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-release:
    uses: StrikerRockers-Mods/.github/.github/workflows/build-release.yml@main
    secrets: inherit
    with:
      forge-cf-id: 292430
      fabric-cf-id: 292430
      modrinth-id: HmStsrlQ